exec swaybg -c "#505050"
workspace_layout default
gaps inner 10 
gaps outer 20 
default_border pixel 2
focus_on_window_activation urgent
default_orientation auto
client.focused           #8a8a8a #2b2b2b #ffffff #8a8a8a #8a8a8a
client.unfocused         #3a3a3a #1c1c1c #8f8f8f #3a3a3a #3a3a3a
client.focused_inactive  #5a5a5a #252525 #cfcfcf #5a5a5a #5a5a5a
client.urgent            #d65d5d #2b2b2b #ffffff #d65d5d #d65d5d
