[config]

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/colors.conf'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/fuzzel.ini'

[templates.mako]
input_path = '~/.config/matugen/templates/mako'
output_path = '~/.config/mako/config'

[templates.telegram]
input_path = '~/.config/matugen/templates/telegram.tdesktop-theme'
output_path = '~/.config/telegram/theme.tdesktop-theme'
