#!/bin/bash

page=1

displayconfs () {
    if [ "$1" -eq 1 ]; then
        clear 
        echo "1 - niri"
        echo "2 - hypr"
        echo "3 - nvim"
        echo "4 - waybar" 
        echo "5 - fuzzel"
    elif [ "$1" -eq 2 ]; then
      clear
      echo "6 - happ"
      echo "7 - grub"
      echo "8 - xdg"
      echo "9 - xdg-desktop-portal"
      echo "10 - mako"
    elif [ "$1" -eq 3 ]; then
        clear
        echo "11 - firefox"
        echo "12 - tlp"
        echo "13 - gtk3"
        echo "14 - gtk4"
        echo "15 - kitty"
    elif [ "$1" -eq 4 ]; then
        clear
        echo "16 - fish"
        echo "17 - driftwm"
        echo "18 - caelestia"
    fi
}

edit_config() {
    if [ $1 = '1' ]; then
        nvim ~/.config/niri/.

    elif [ $1 = '2' ]; then
        nvim ~/.config/hypr/

    elif [ $1 = '3' ]; then
        nvim ~/.config/nvim/
    
    elif [ $1 = '4' ]; then
        nvim ~/.config/waybar/
    
    elif [ $1 = '5' ]; then
        nvim  ~/.config/fuzzel/

    elif [ $1 = '6' ]; then 
        nvim ~/.config/Happ.conf

    elif [ $1 = '7' ]; then
        nvim ~/.config/grub/grub
        sudo grub-mkconfig -o /boot/grub/grub.cfg
    
    elif [ $1 = '8' ]; then
        nvim ~/.config/xdg/user-dirs.conf

    elif [ $1 = '9' ]; then
        nvim ~/.config/xdg-desktop-portal/niri-portals.conf

    elif [ $1 = '10' ]; then
        nvim ~/.config/mako/

    elif [ $1 = '11' ]; then
        cd ~/.config/mozilla/firefox/8hqennow.default-release/

    elif [ $1 = '12' ]; then
        nvim ~/.config/tlp/tlp.conf 

    elif [ $1 = '13' ]; then
        nvim ~/.config/gtk-3.0/settings.ini

    elif [ $1 = '14' ]; then
        nvim ~/.config/gtk-4.0/settings.ini

    elif [ $1 = '15' ]; then
        nvim ~/.config/kitty/kitty.conf

    elif [ $1 = '16' ]; then
        nvim ~/.config/fish/

    elif [ $1 = '17' ]; then
        nvim ~/.config/driftwm/config.toml

    elif [ $1 = '18' ]; then
        nvim ~/.config/caelestia/shell.json

    fi

}

while [ "$page" -gt 0 ] && [ "$page" -lt 5 ]

do
    displayconfs $page
    echo "$page"
    echo "page conf-num, next, prev (c, n, p, q)"
    read next_page
    if [ "$next_page" = 'n' ]; then
        if [ "$page" -eq 4 ]; then
            continue 
        fi
        page+=1
    fi
    if [ "$next_page" = 'p' ]; then
        if [ "$page" -eq 1 ]; then
            continue 
        else
            page-=1
        fi
    fi
    if [ "$next_page" = 'q' ]; then
        break
    fi

    if [ "$next_page" -gt 0 ] && [ "$next_page" -lt 19 ]; then 
        edit_config $next_page
        break 
    fi
done


