-- Generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#1a1110",
	base01 = "#140c0b",
	base02 = "#231918",
	base03 = "#534341",
	base04 = "#d8c2bf",
	base05 = "#f1dedc",
	base06 = "#392e2d",
	base07 = "#423735",

	base08 = "#dbb978",
	base09 = "#e0c38c",
	base0A = "#e7bdb8",
	base0B = "#ffb4ab",
	base0C = "#584419",
	base0D = "#73332e",
	base0E = "#5d3f3c",
	base0F = "#da9a92",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#73332e",
	fg = "#ffdad6", -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ "String", "TSString" }, {
	fg = "#d0a450",
})

-- Grey out comments
set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#a08c8a",
	italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#e0c38c",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#e7bdb8",
})

set_hl_mutliple({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
	fg = "#904a43",
})


