-- Generated by Matugen

require("base16-colorscheme").setup({
	base00 = "#12140d",
	base01 = "#0d0f08",
	base02 = "#1b1c15",
	base03 = "#45483c",
	base04 = "#c6c8b8",
	base05 = "#e3e3d7",
	base06 = "#303129",
	base07 = "#383a32",

	base08 = "#90c8bd",
	base09 = "#a1d0c7",
	base0A = "#c3caaa",
	base0B = "#bacf83",
	base0C = "#204e47",
	base0D = "#3c4d0e",
	base0E = "#434931",
	base0F = "#adb68b",
})

-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
	for _, v in pairs(groups) do
		vim.api.nvim_set_hl(0, v, value)
	end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, "Visual", {
	bg = "#3c4d0e",
	fg = "#d6eb9c", -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ "String", "TSString" }, {
	fg = "#6eb7a9",
})

-- Grey out comments
set_hl_mutliple({ "TSComment", "Comment" }, {
	fg = "#909284",
	italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ "TSMethod", "Method" }, {
	fg = "#a1d0c7",
})

set_hl_mutliple({ "TSFunction", "Function" }, {
	fg = "#c3caaa",
})

set_hl_mutliple({ "Keyword", "TSKeyword", "TSKeywordFunction", "TSRepeat" }, {
	fg = "#536525",
})


