-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#17130b",
  base01 = "#110e07",
  base02 = "#1f1b13",
  base03 = "#4d4639",
  base04 = "#d0c5b4",
  base05 = "#ebe1d4",
  base06 = "#353027",
  base07 = "#3e382f",

  base08 = "#a2c699",
  base09 = "#b1cfa9",
  base0A = "#d8c4a0",
  base0B = "#eac16c",
  base0C = "#334d30",
  base0D = "#5c4300",
  base0E = "#53452a",
  base0F = "#c9ae7c",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#5c4300',
  fg = '#ffdea0', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '#84b478',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#998f80',
  italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#b1cfa9',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#d8c4a0',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#785a0b',
})

require('lualine').setup({
  options = {
    theme = "base16",
  }
})
